# 古典暗号

## 古典暗号とは

- 古典暗号と現代暗号を区別する明確な定義はない
- ここではコンピュータを使うかどうかで区別する
    1. 古典暗号:
        - コンピュータ登場以前の暗号
        - 鍵の総数が少なくアルゴリズムが単純なため、アルゴリズムを非公開にして使用しないとすぐに解読されてしまう
    2. 現代暗号:
        - コンピュータ登場以降の暗号
        - 複雑なアルゴリズムを採用することにより、アルゴリズムが公開されていても解読されにくい


## 平文空間と暗号文空間

- 平文空間:
    - 平文として使用される文字の集まり（暗号化される前のテキスト）
- 暗号文空間:
    - 暗号文として使用される文字の集まり
    - 平文空間と暗号文空間は同一空間に存在していることもある
        - 例: アルファベットから成る平文を、でたらめなアルファベットの羅列に暗号化した場合など
            - 同じ文字の集まりを使っているため、同一空間に属していると言える
        - 一方、アルファベットから成る平文を、全く別の絵文字や記号に変換した場合、平文空間と暗号文空間は異なると言える

### 古典暗号における平文空間と暗号文空間
- 古典暗号において、平文は読める文字であることが大半
- 古典暗号: 平文空間から暗号文空間への写像
    - 古典暗号 = `f(平文空間の元) -> 暗号文空間の元` の変換を行う関数f
    - 例（平文空間＝暗号文空間の場合）:
        - `f(["a", "b", ..., "z"]) -> ["c", "d", ..., "b"]`
    - 例（平文空間≠暗号空間の場合）:
        - `f(["a", "b", ..., "z"]) -> ["!", "#", ..., "_"]`

- ※写像とは
    - 二つの集合が与えられたときに、一方の集合の各元に対し、他方の集合のただひとつの元を指定して結びつける対応のこと
        - ※元とは: 集合を構成する要素のこと

### 現代暗号における平文空間と暗号文空間
- 現代暗号において、平文はコンピュータにとって扱いやすい数字（符号）である
    - 数字の符号は、現代暗号のアルゴリズムで扱うにも都合が良い
- 読める文字だけでなく、空白や句読点などの記号も符号化の対象とすることであらゆる文章を平文空間に持ち込むことができる
- 現代暗号: 文字／記号の集合を符号化した平文空間から暗号文空間への写像
    - 符号化: `f(文章[文字／記号の集合]) -> 平文空間[符号の集合]`
    - 暗号化: `f(平文空間[符号の集合]) -> 暗号文空間[符号の集合]`

## シーザー暗号

- 暗号化アルゴリズム:
    - 平文のアルファベットをそれぞれ3文字ずらす（アルファベットの最後の3文字は先頭に循環させる）
        1. KeyGen（鍵生成アルゴリズム）
            - `KeyGen(起動) -> n = 3（固定）`
        2. Enc（暗号化アルゴリズム）
            - `Enc(平文, 鍵) -> 各文字を右に(鍵)文字ずらした暗号文を生成`
        3. Dec（復号アルゴリズム）
            - `Dec(暗号文, 鍵) -> 各文字を左に(鍵)文字ずらした平文を生成`

#### シーザー暗号対応表
 a | b | c | d | e | f | g | h | i | j | k | l | m | n | o | p | q | r | s | t | u | v | w | x | y | z
:--|:--|:--|:--|:--|:--|:--|:--|:--|:--|:--|:--|:--|:--|:--|:--|:--|:--|:--|:--|:--|:--|:--|:--|:--|:--|
 d | e | f | g | h | i | j | k | l | m | n | o | p | q | r | s | t | u | v | w | x | y | z | a | b | c
 

In [1]:
# シーザー暗号
module Caesar
    ## 鍵生成: n = 3
    KeyGen() = (n = 3)

    ## 暗号化: 暗号文[i] = (平文[i] + n) % 26
    ### アルファベットの列を循環させるために、文字符号をn文字右にずらしたあと 26 で割った余りを求める
    Enc(text::AbstractString, n::Int) = [c = Char((Int(c) + n) % 26) for c in text]

    ## 復号: 平文[i] = (暗号文[i] + 26 - n) % 26
    ### アルファベットの列を循環させるために、文字符号をn文字左にずらしたあと 26 で割った余りを求める
    Dec(text::AbstractString, n::Int) = [c = Char((Int(c) + 26 - n) % 26) for c in text]
end

Main.Caesar

In [2]:
# シーザー暗号: 動作確認
Caesar.Enc("\0\1\2", Caesar.KeyGen())

3-element Array{Char,1}:
 '\x03'
 '\x04'
 '\x05'

In [3]:
# 今のままではアルファベットをそのまま使えないため、符号化を行うアルゴリズムを定義する

## アルファベット["a", "b", ..."z"] -> 符号[0, 1, ..., 26]
### アスキーコード表より 'a' = 97, ...'z' = 122
### -> ret[i] = text[i] - 97
encode(text::AbstractString)::Array{Char,1} = [Char(Int(c) - 97) for c in text]

## 符号[0, 1, ..., 26] -> アルファベット["a", "b", ..., "z"]
### ret[i] = signs[i] + 97
decode(signs::Array{Char,1})::AbstractString = String([Char(Int(c) + 97) for c in signs])

decode (generic function with 1 method)

In [4]:
# 動作確認
encode("helloworld")

10-element Array{Char,1}:
 '\a'  
 '\x04'
 '\v'  
 '\v'  
 '\x0e'
 '\x16'
 '\x0e'
 '\x11'
 '\v'  
 '\x03'

In [5]:
decode(['\20', '\10', '\0'])

"qia"

In [6]:
# 符号化を含めてシーザー暗号を実装
module Caesar
    import ..encode, ..decode

    ## 鍵生成: n = 3
    KeyGen() = (n = 3)

    ## 暗号化: 暗号文[i] = (平文[i] + n) % 26
    ### アルファベットの列を循環させるために、文字符号をn文字右にずらしたあと 26 で割った余りを求める
    Enc(text::AbstractString, n::Int)::AbstractString = String(decode([c = Char((Int(c) + n) % 26) for c in encode(text)]))

    ## 復号: 平文[i] = (暗号文[i] + 26 - n) % 26
    ### アルファベットの列を循環させるために、文字符号をn文字左にずらしたあと 26 で割った余りを求める
    Dec(text::AbstractString, n::Int)::AbstractString = String(decode([c = Char((Int(c) + 26 - n) % 26) for c in encode(text)]))
end

Main.Caesar

In [7]:
# 動作確認
enc = Caesar.Enc("helloworld", Caesar.KeyGen())
println(enc) # 暗号文

dec = Caesar.Dec(enc, Caesar.KeyGen())
println(dec) # 平文

khoorzruog
helloworld


### シーザー暗号の現代暗号対応
- 上記のプログラムを見てもわかるように、古典暗号をコンピュータ上で再現しようとすると無駄な処理が増える
- やはりコンピュータで計算させるのであれば、平文空間／暗号化文空間を符号の集合で表現するのが最も効率的
    - さらに言えば、記号類も符号化することにより、より自然な文章の平文を扱うこともできる

#### シーザー暗号のコンピュータアルゴリズム
- 符号化: `f(平文::AbstractString) -> 平文空間::Array{Int,1}`
    - 符号の集合を整数の1次元配列で表現する
- 暗号化: `f(平文空間::Array{Int,1}) -> 暗号文空間::Array{Int,1}`
    - KeyGen: `f(起動) -> n = 3`
    - Enc: `f(平文空間::Array{Int,1}, n::Int) -> 元 += n`
    - Dec: `f(暗号文空間::Array{Int,1}, n::Int) -> 元 -= n`
- 文字列化: `f(平文空間::Array{Int,1}) -> 平文::AbstractString`
    - 符号の集合を文字列に戻す

In [8]:
# シーザー暗号（現代暗号最適化版）
module NewCaesar
    # 鍵生成: f() -> n = 3
    KeyGen()::Int = 3
    
    # 暗号化: f(平文空間, 鍵) -> 元 += 鍵
    ## Julia の `.` 演算子は、関数を配列の各要素に対して適用する
    Enc(signs::Array{Int,1}, n::Int)::Array{Int,1} = signs .+= n

    # 復号: f(暗号文空間, 鍵) -> 元 -= 鍵
    Dec(signs::Array{Int,1}, n::Int)::Array{Int,1} = signs .-= n
end

# 符号化: f(平文::AbstractString) -> 符号空間::Array{Int,1}
encode(text::AbstractString)::Array{Int,1} = [Int(c) for c in text]

# 文字列化: f(符号空間::Array{Int,1}) -> 平文::AbstractString
decode(signs::Array{Int,1})::AbstractString = String([Char(c) for c in signs])

decode (generic function with 2 methods)

In [9]:
# 動作確認
enc = NewCaesar.Enc(encode("Hello, World!"), NewCaesar.KeyGen())
println(enc) # 暗号文

## |> パイプ演算子: 直前の式の結果を直後の関数の第1引数に渡す
### -> decode(NewCaesar.Dec(enc, NewCaesar.KeyGen()))
dec = NewCaesar.Dec(enc, NewCaesar.KeyGen()) |> decode
println(dec) # 平文

[75, 104, 111, 111, 114, 47, 35, 90, 114, 117, 111, 103, 36]
Hello, World!


## シフト暗号

- シーザー暗号は文字をずらす値を3に固定していたが、ずらす値を任意とする方法をシフト暗号と呼ぶ
- ずらす値は鍵に相当するため、送受信者以外には秘密にする必要がある

In [10]:
# シフト暗号
module Shift
    # 鍵生成: f() -> n = 1〜10の乱数
    KeyGen()::Int = rand(1:10)
    
    # 暗号化: f(平文空間::Array{Int,1}, 鍵::Int) -> 暗号文空間[i] = 平文空間[i] + 鍵
    Enc(signs::Array{Int,1}, n::Int)::Array{Int,1} = signs .+= n

    # 復号: f(平文空間::Array{Int,1}, 鍵::Int) -> 暗号文空間[i] = 平文空間[i] - 鍵
    Dec(signs::Array{Int,1}, n::Int)::Array{Int,1} = signs .-= n
end

# 動作確認
key = Shift.KeyGen() # 鍵 = ずらす値

enc = Shift.Enc(encode("Hello, World!"), key)
println(enc) # 暗号文

dec = Shift.Dec(enc, key) |> decode
println(dec) # 平文

[73, 102, 109, 109, 112, 45, 33, 88, 112, 115, 109, 101, 34]
Hello, World!


## コード

- 仲間内でしか通用しない合言葉を拡張したもの
    - 合言葉の対応表をコードブックと呼ぶ
- コードブックを作成するのに膨大な時間がかかる
- コードブックは丸暗記に向いていないため、配送・携帯・管理に問題が生じる

### コードのアルゴリズム
- コードブックを参照し、特定のキーワードに一致した部分を合言葉に置換する
    - 鍵生成: `KeyGen() -> コードブック::Array{Tuple{String,String},1}`
        - コードブック: 2つの文字列（キーワード, 合言葉）のタプルを1次元配列で表現
    - 暗号化: `Enc(平文空間::String, コードブック) -> 暗号文空間::String`
        - 適用: `replace(平文空間::String, キーワード::String, 合言葉::String)`
    - 復号: `Dec(暗号文空間::String, コードブック) -> 平文空間::String`
        - 適用: `replace(暗号文空間::String, 合言葉::String, キーワード::String)`

In [11]:
# コード
module Code

## 鍵生成
KeyGen()::Array{Tuple{AbstractString,AbstractString},1} = [
    ("apple", "バナナ"), ("Hello", "byebye"), ("world", "りんご"),
    ("バナナ", "milky"), ("I'm", "!?!?@^^;"), (", ", "hogeほげ!"),
    ("1988", "_8891_@"), ("Boy", "ジュリア"), ("Girl", "womanma"),
]

## 暗号化
Enc(
    text::AbstractString,
    book::Array{Tuple{AbstractString,AbstractString},1}
)::AbstractString = begin
    for words in book
        text = replace(text, words[1] => words[2])
    end
    text
end

## 復号
Dec(
    text::AbstractString,
    book::Array{Tuple{AbstractString,AbstractString},1}
)::AbstractString = begin
    for words in book
        text = replace(text, words[2] => words[1])
    end
    text
end

end

Main.Code

In [12]:
# 動作確認
text = """
Hello, world!
I'm appleバナナ at 1988.
Boys and Girls be ambisious!
"""
enc = Code.Enc(text, Code.KeyGen())
println(enc) # 暗号文

dec = Code.Dec(enc, Code.KeyGen())
println(dec) # 平文

byebyehogeほげ!りんご!
!?!?@^^; milkymilky at _8891_@.
ジュリアs and womanmas be ambisious!

Hello, world!
I'm バナナバナナ at 1988.
Boys and Girls be ambisious!



## スキュタレー暗号

- 暗号文が帯状のものに記述されるため秘密通信と相性が良い
    - 例えば、ベルトにすることで隠して運搬することなどが可能
- スキュタレー暗号を一般化すると転置式暗号に拡張できる
- 仕組み:
    1. 帯状の羊皮紙を特定の太さの筒に斜めに巻きつける
    2. 筒に巻きつけた状態の帯に平文を書き込む
    3. 余白は無意味な文字で埋める
    4. 巻きつけた羊皮紙を解くと、無意味な文字列となっている
        - 要するに縦読みの応用

### スキュタレー暗号のアルゴリズム
- 鍵生成: `KeyGen() -> 筒の直径::Int`
    - 筒の直径は秘密にしておかなければならない
- 暗号化: `Enc(平文::String, 筒の直径::Int) -> 暗号文::String`
    1. 平文を筒の直径に合わせて分割
        - `平文 / 筒の直径 -> Array{Array{Char,1},1}`
    2. 分割した文字列配列の最後の文字列が筒の直径の長さに足りていない場合は、ランダムな文字列で埋める
    3. 文字列配列の行列を転置する
    4. 再び1つの文字列につなげる
- 復号化: 暗号化の逆を行えば良い

In [13]:
import Base: /

# 標準関数 `/` に機能追加
## 文字列を数値分の長さごとに分割 -> Array{Array{Char,1},1}
/(str::AbstractString, n::Int) = begin
    result = [[]]
    cur = result[1]
    for c in str
        if length(cur) === n
            cur = []
            push!(result, cur)
        end
        push!(cur, c)
    end
    result
end

# 動作確認
array = "雨降って地固まるぞ" / 4

# 長さが足りない場合はランダムな文字で埋める
if length(array[end]) < 4
    array[end] = vcat(array[end], rand(Char, 4 - length(array[end])))
end

array

3-element Array{Array{Any,1},1}:
 ['雨', '降', 'っ', 'て']                  
 ['地', '固', 'ま', 'る']                  
 ['ぞ', '\Ua1e62', '\U9340e', '\U89450']

In [14]:
# 縦読みで文字列を再構築
str = ""
for i = 1:4
    for row in array
        str *= string(row[i])
    end
end
str

"雨地ぞ降固\Ua1e62っま\U9340eてる\U89450"

### スキュタレー暗号の効率化
- 平文を文字列のまま扱うとUTF-8文字などの関係で行列への変換コストがかかる
- また、permutedimsなどの行列操作関数を使うこともできず、非効率的
- 符号空間に変換してから、スキュタレー暗号化することで効率的な処理が可能

#### 符号化スキュタレー暗号のアルゴリズム
- 暗号化: `Enc(平文空間::Array{Int,1}, 筒の直径::Int) -> 暗号文空間::Array{Int,1}`
     1. 符号配列の長さが筒の直径で割り切れない場合は、足りない分をランダムなChar型整数で埋める
     2. 符号配列を筒の直径に合わせて分割
         - `平文 / 筒の直径 -> Array{Array{Int,1},1}`
     3. 行列を転置する
     4. 1次元配列にreshape
- 復号: 暗号化の逆の手順で行う

In [15]:
# テスト
r = reshape([1,2,3,4,5,6,7,8,9,10], (2,:))

2×5 Array{Int64,2}:
 1  3  5  7   9
 2  4  6  8  10

In [16]:
t = permutedims(r, (2, 1)) # 行,列 -> 列,行 に転置

5×2 Array{Int64,2}:
 1   2
 3   4
 5   6
 7   8
 9  10

In [17]:
e = reshape(t, length(t))

10-element Array{Int64,1}:
  1
  3
  5
  7
  9
  2
  4
  6
  8
 10

In [18]:
# 元に戻す
reshape(e, (:,2)) |> # 5x2行列に変換
    (x) -> permutedims(x, (2, 1)) |> # 転置行列 2x5
        (x) -> reshape(x, :) # 1次元配列に戻す

10-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [19]:
# スキュタレー暗号
module Scutalay

## 鍵生成: 2〜10の乱数
KeyGen()::Int = rand(2:10)

## 暗号化
Enc(signs::Array{Int,1}, r::Int)::Array{Int,1} = (
        length(signs) % r > 0 ?
        # 長さが足りない分を乱数で埋める
        signs = vcat(signs, rand(Char, r - length(signs) % r)) : signs
    ) |>
    # r x ? 行列に変換
    (x) -> reshape(x, (r, :)) |>
    # ? x r 転置行列
    (x) -> permutedims(x, (2, 1)) |>
    # Array{Int,1}配列に戻す
    (x) -> reshape(x, :)

## 復号 -> 平文にして返す
Dec(signs::Array{Int,1}, r::Int)::AbstractString = String([
        Char(c) for c in (
            reshape(signs, (:, r)) |>
                (x) -> permutedims(x, (2, 1)) |>
                (x) -> reshape(x, :)
        )
    ])

end

Main.Scutalay

In [20]:
# 動作確認

r = Scutalay.KeyGen() # 秘密にしなければならない筒の直径

# 平文
text = """
Hello, world!
I'm appleバナナ at 1988.
Boys and Girls be ambisious!
"""

signs = encode(text)
println(signs) # 符号

enc = Scutalay.Enc(encode(text), r)
println(enc) # 暗号文

dec = Scutalay.Dec(enc, r)
println(dec) # 平文

[72, 101, 108, 108, 111, 44, 32, 119, 111, 114, 108, 100, 33, 10, 73, 39, 109, 32, 97, 112, 112, 108, 101, 12496, 12490, 12490, 32, 97, 116, 32, 49, 57, 56, 56, 46, 10, 66, 111, 121, 115, 32, 97, 110, 100, 32, 71, 105, 114, 108, 115, 32, 98, 101, 32, 97, 109, 98, 105, 115, 105, 111, 117, 115, 33, 10]
[72, 108, 32, 114, 33, 39, 97, 108, 12490, 97, 49, 56, 66, 115, 110, 71, 108, 98, 97, 105, 111, 33, 101, 111, 119, 108, 10, 109, 112, 101, 12490, 116, 57, 46, 111, 32, 100, 105, 115, 101, 109, 115, 117, 10, 108, 44, 111, 100, 73, 32, 112, 12496, 32, 32, 56, 10, 121, 97, 32, 114, 32, 32, 98, 105, 115, 434336]
Hello, world!
I'm appleバナナ at 1988.
Boys and Girls be ambisious!
񪂠


## 転置式暗号

- アナグラムの応用的な暗号化方式
- 従来の暗号の鍵は数十通りだったが、転置式暗号の鍵は数百通りになる
- 現代暗号でも利用されている
- 仕組み:
    - 基本的には、スキュタレー暗号の「行列転置」部分を「特定のルールに従って転置する」という方式に一般化したもの
        1. 平文を適当な数で分割する
        2. 分割した文字列の行列に対して転置関数（文字入れ替えのルール）を適用する
        3. 分割した文字列を結合して暗号文とする

### 転置式暗号のアルゴリズム
スキュタレー暗号同様、符号の集合を平文空間として扱ったほうが効率が良いため、符号化してアルゴリズムを適用する

1. 鍵生成:
    - `KeyGen() -> n = 分割文字数::Int, τ = 置換規則::Function`
    - 置換規則: `τ(Array{Int,2}) -> Array{Int,2}`
        - 平文空間が分割された2次元配列（行列）を転置する関数
2. 暗号化:
    - `Enc(平文空間::Array{Int,1}, n::Int, τ::Function) -> 暗号文空間::Array{Int,1}`
        1. 平文空間分割: `平文空間 / n -> 平文行列::Array{Int,2}`
        2. 置換規則適用: `τ(平文行列) -> 暗号文行列::Array{Int,2}`
        3. 暗号文空間化: `reshape(暗号文行列, :) -> 暗号文空間::Array{Int,2}`
3. 復号:
    - `Dec(暗号文空間::Array{Int,1}, n::Int, τ^-1::Function) -> 平文空間::Array{Int,1}`
        - τ^-1: 置換規則の逆操作

#### 鍵の決め方
- 暗号の仕様を決定する段階では平文の長さはわからない
    - -> 平分の長さに応じて暗号の仕様を決定するのは不可能
- 仕様決定の際には、分割文字数と平分の文字数の関係によって、以下のような結果に成ることを考慮する必要がある
    1. 「分割文字数 = 平文文字数」の場合
        - 平文をシャッフルした状況と同等
    2. 「分割文字数 > 平文文字数」の場合
        - 平文にパディングして文字数を分割文字数と一致させるなどの工夫が必要になる
        - ただし、パディングに使用した文字が自明であると置換規則解読のヒントになってしまう
    3. 「分割文字数 < 平文文字数」の場合
        - 分割文字数が平文より極端に小さいと暗号化強度が脆弱になる
        - 極端な話、分割文字数が1だと暗号化は行われない

### 転置式暗号の鍵数
- 分割文字数を4とした場合、置換規則の総数は次のように計算できる
    - `置換規則の総数 = 4! = 4 * 3 * 2 * 1 = 24`
- 解読者が分割文字数を6以下であると推測した場合、n = 2, 3, ..., 6 を総当りで計算することになるため、探索する置換規則の候補数は次のようになる
    - `置換規則の総数 = 2! + 3! + 4! + 5! + 6! = 872`
- このように、転置式暗号の鍵の候補は、これまでの古典暗号に比べて格段に多く、総当り解読に対して高い強度を持っている

## 単一換字式暗号

- 単一換字式暗号の鍵の総数は膨大であるため、単純な総当り攻撃に対しては高い暗号強度を持つ
- 単一換字式暗号を解読する場合は、頻度分析という解読手法が使われる
- 文字の換字（置き換え）という考え方は、現代暗号でも利用される

### 換字式暗号の仕組み
- 平文の文字を別の文字や記号に対応させる暗号のことを換字式暗号と呼ぶ
- 特に平文と暗号文の1文字が1対1で対応しているものを単一換字式暗号と呼ぶ
    - シーザー暗号やシフト暗号も単一換字式暗号の一種
- ある文字を別の文字に変換するルールを変換規則σで表す
    - `σ(平文文字::Char) -> 暗号文文字::Char`

### 単一換字式暗号のアルゴリズム
- 鍵生成: `KeyGen() -> σ::Function`
    - 変換規則: `σ(平文文字::Char) -> 暗号文文字::Char`
- 暗号化: `Enc(平文空間::String, σ::Function) -> 暗号文空間::String`
    - 平文空間の各文字（元）に対して変換規則σを適用
- 復号: `Dec(暗号文空間::String, σ^-1::Function) -> 平文空間::String`
    - σ^-1: 変換規則の逆操作

### 単一換字式暗号の鍵数
- アルファベット26文字の変換規則パターン（鍵）の総数は以下の通り
    - `変換規則の総数 = 26! ≒ 4.0×10^26`
- これは極めて巨大な数であり、総当たりによる鍵の探索はほぼ不可能である

In [21]:
# 単一換字式暗号
module CharReplacer

## 鍵生成: 変換規則 σ(Char)->Char を生成
### 変換規則:
### - 文字コードが偶数 => 右に9ずらす
### - 文字コードが奇数 => 左に9ずらす
KeyGen() = (c::Char) -> begin
    c = Int(c)
    c % 2 == 0 && return Char(c + 9)
    return Char(c - 9)
end

## 暗号化: 平文空間に鍵（変換規則）を適用
Enc(text::AbstractString, σ)::AbstractString = String([σ(c) for c in text])

## 復号: 平文空間に鍵（変換規則の逆操作）を適用
### 今回の場合、変換規則の逆操作 = 変換規則
Dec(text::AbstractString, σ)::AbstractString = String([σ(c) for c in text])

end

Main.CharReplacer

In [22]:
# 動作確認
key = CharReplacer.KeyGen() # 鍵 = 変換関数

enc = CharReplacer.Enc("Hello, World!", key)
println(enc) # 暗号文

dec = CharReplacer.Dec(enc, key)
println(dec) # 平文

Q\uuf5)Nf{um
Hello, World!
